---
latitude: 42.06702
longitude: -88.07871
map_zoom: 12
name: Radisson Hotel Schaumburg
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 1998 North Roselle Road
  street2: ''
  state: Illinois
  city: Schaumburg
  country: United States
  zip_code: '60195'
_hotel_id: RAD894
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
